apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  containers:
  - name: endpoint
    image: alpine:3.5
    args:
    - sh
    - -c
    - while true; do ( echo "HTTP/1.0 200 Ok"; echo; echo "OK" ) | nc -lp 80; done

---

apiVersion: v1
kind: Service
metadata:
  name: test
spec:
#  type: NodePort
  ports:
  - protocol: TCP
    port: 80
 #   nodePort: 80
    name: http
  selector:
    app: test